### ISSUE TITLE
Is it possible to do a VDAgent display resize  with PureSpice ?

### ISSUE THREAD

**Issue by vitoo** [gnif/PureSpice#13]
Hello @gnif :)

i've seen in the code that PureSpire can do copy paste with VDAgent 

From a custom spice client i'm building, i try to implement the VDAgent screen resize (resolution change), and i used some PureSpice sample to do it.

On a windows VM, It works one time (resolution is updated) then the vdagent.exe freeze, without restarting, and the spice client lost connection to vdagent.
In the vdagent.log the only anormal thing i noticed is that the chunk->hdr.port is 0, when using virt-viewer the hdr.port is 1. 
So i should be doing something wrong, here is how i send the message bellow :

Maybe you can see what i am doing wrong ?
Thanks a lot !

```c
typedef struct SPICE_ATTR_PACKED _VDAgentMonitorsConfig {
    uint32_t num_of_monitors;
    uint32_t flags;
    uint32_t height;
    uint32_t width;
    uint32_t depth;
    uint32_t x;
    uint32_t y;
} _VDAgentMonitorsConfig;


_VDAgentMonitorsConfig reqMonitor;
const ssize_t monitorSize = sizeof(_VDAgentMonitorsConfig);
reqMonitor.num_of_monitors = 1;
reqMonitor.flags = 0;
reqMonitor.height = height;
reqMonitor.width = width;
reqMonitor.depth = 32;
reqMonitor.x = 0;
reqMonitor.y = 0;

spice_agent_start_msg(VD_AGENT_MONITORS_CONFIG, monitorSize);
spice_agent_write_msg(&reqMonitor, monitorSize);


bool spice_agent_start_msg(uint32_t type, ssize_t size)
{
    VDAgentMessage* msg = SPICE_PACKET_MALLOC(SPICE_MSGC_MAIN_AGENT_DATA, VDAgentMessage, 0);

    msg->protocol = VD_AGENT_PROTOCOL;
    msg->type = type;
    msg->opaque = 0;
    msg->size = size;
    spice.agentMsg = size;
    queue_push(spice.agentQueue, msg);

    return spice_agent_process_queue();
}

bool spice_agent_write_msg(const void* buffer, ssize_t size)
{
    assert(size <= spice.agentMsg);

    while (size)
    {
        const ssize_t toWrite = size > VD_AGENT_MAX_DATA_SIZE ? VD_AGENT_MAX_DATA_SIZE : size;

        void* msg = SPICE_RAW_PACKET_MALLOC(SPICE_MSGC_MAIN_AGENT_DATA, toWrite, 0);
        memcpy(msg, buffer, toWrite);
        queue_push(spice.agentQueue, msg);

        size -= toWrite;
        buffer += toWrite;
        spice.agentMsg -= toWrite;
    }

    return spice_agent_process_queue();
}


```

**Comment by gnif** [comment]
The vdagent.exe process is very finicky about proper protocol handling, it's likely you're getting a response from the agent you're not handling. I have never looked into the monitor handling code of the protocol as it is outside the scope of what spice is being used for in Looking Glass.

**Comment by vitoo** [comment]
Thanks, it works with the spice-client-glib

**Comment by vitoo** [comment]
But with this lib i can't click and drag with the mouse, to select text for example.

I could not hold a keyboard key and get repeat (like pressing b and having : bbbbbbbbbbbb ) until i set this device 

-device virtio-keyboard 

But for mouse i cannot find a way :(  You have an idea to fix this ? @gnif

**Comment by gnif** [comment]
Remove the virtual tablet device from the VM

**Comment by vitoo** [comment]
I think i dont have this

In proxmox : "use tablet for pointer = No"

qemu : 
args: -device virtio-keyboard -device usb-mouse

**Comment by gnif** [comment]
in any case, this is not a support channel and I have no experience with Proxmox.

**Comment by vitoo** [comment]
Sure, thanks for your help
