### ISSUE TITLE
cannot build with clang: variable length array in structure

### ISSUE THREAD

**Issue by harikattar** [gnif/PureSpice#3]
If this can only be built with GCC it should be forced in the cmakefiles

Clang gives:
LookingGlass/repos/PureSpice/src/rsa.c:101:13: error: fields must have a constant size:
      'variable length array in structure' extension will never be supported
    uint8_t db [key_size - SHA1_HASH_LEN - 1];

Alternate fix would be to define and enforce a maximum keysize.

**Comment by harikattar** [comment]
Potential fix: use a zero-size array and alloca():

https://gist.github.com/harikattar/762e8414bcc57b3959c4e0f46b8bec46

I tested a simplified version of the code on godbolt.org and everything appears sane.

https://godbolt.org/z/5mmqzQ

![compare_vlas_to_alloca_000](https://user-images.githubusercontent.com/2084701/81263325-762f3000-900d-11ea-8c6a-909f55bb0b83.png)

**Comment by thrifty-txt** [comment]
I'd like to confirm that this issue still blocks Clang/LLVM 11 built Looking Glass.

**Comment by gnif** [comment]
thanks, yes, I will update this to use `alloca`, we already had done the same in other areas for the same reason. I am not specifically targetting clang/llvm, however, it's easy enough to be compatible with it ;)
